language: node_js
node_js:
  - "node"

cache:
  directories:
  - node_modules

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: dist
  on:
    branch: master
